### ISSUE TITLE
Missing information: how many SAP HANA hosts by storage host

### ISSUE THREAD

**Issue by valuial** [NetAppDocs/netapp-solutions-sap#13]
Page: [Storage sizing](https://docs.netapp.com/us-en/netapp-solutions-sap/bp/saphana_aff_nfs_storage_sizing.html)

You Write:
NetApp tested and predefined the maximum number of SAP HANA hosts that can be attached to a specific storage model while still fulfilling the required storage KPIs from SAP for production-based SAP HANA systems.

Missing Information: Where can I find a table with the storage models maximum SAP HANA systems to be attached?

**Comment by netapp-mschoen** [comment]
Please get in contact with our solution architects or  your sales representative to get the right solution for your environment.
