### ISSUE TITLE
Links to "SAP HANA on NetApp FAS Systems with xxx" are dead

### ISSUE THREAD

**Issue by okrause** [NetAppDocs/netapp-solutions-sap#15]
Page: [TR-4435: SAP HANA on NetApp AFF Systems with NFS - Configuration Guide](https://docs.netapp.com/us-en/netapp-solutions-sap/bp/saphana_aff_nfs_introduction.html)
"The configuration guides for NetApp AFF systems using FCP and for FAS systems using NFS or FCP can be found at the following links:

SAP HANA on NetApp FAS Systems with Fibre Channel Protocol

SAP HANA on NetApp FAS Systems with NFS

SAP HANA on NetApp AFF Systems with Fibre Channel Protocol

"
All three links are dead.

**Comment by netapp-mschoen** [comment]
Links have been updated to the correct location.
