### ISSUE TITLE
NAE also supported with SAP HANA?

### ISSUE THREAD

**Issue by Myer** [NetAppDocs/netapp-solutions-sap#48]
### Page URL

https://docs.netapp.com/us-en/netapp-solutions-sap/bp/saphana_aff_nfs_storage_controller_setup.html

### Page title

Storage controller setup

### Summary

It's mentioned that NVE is supported with SAP HANA.
Please confirm if NAE is also supported.

(My guess would be it is supported since in the paragraph before you're saying that cross-volume inline deduplication is supported and that's basically the only reason to use NAE.)

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-mschoen** [comment]
NAE is supported as well. I updated the documentation.
